CREATE TABLE `project_tasks` (
  `id` VARCHAR(30) NOT NULL,
  `projectId` VARCHAR(36) NOT NULL,
  `parentId` VARCHAR(30) NULL,
  `sortOrder` INT NOT NULL DEFAULT 0,
  `kind` VARCHAR(16) NOT NULL DEFAULT 'task',
  `title` VARCHAR(191) NOT NULL,
  `status` VARCHAR(64) NOT NULL DEFAULT '未开始',
  `priority` VARCHAR(32) NOT NULL DEFAULT '普通',
  `startDate` DATETIME(3) NULL,
  `endDate` DATETIME(3) NULL,
  `ownerUserId` VARCHAR(30) NULL,
  `stageTitle` VARCHAR(191) NULL,
  `description` TEXT NULL,
  `progress` INT NOT NULL DEFAULT 0,
  `attachments` INT NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `project_tasks_projectId_idx` (`projectId`),
  INDEX `project_tasks_projectId_parentId_idx` (`projectId`, `parentId`),
  CONSTRAINT `project_tasks_projectId_fkey` FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `project_tasks_parentId_fkey` FOREIGN KEY (`parentId`) REFERENCES `project_tasks`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `project_tasks_ownerUserId_fkey` FOREIGN KEY (`ownerUserId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);
